# -*- coding: utf-8 -*-
"""NAVEED.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xC6yhG-Vc3xCyerX7_KnsHrmiU4WmWUt
"""

# Student name : NAVEED HAYDER
# Cell number : 03441344885
# Email id : mn815325@gmail.com

#QUESTION NO.1: Declare and initialize two variables, num1 and num2, with integer values. Calculate and print their sum.

NUM1 = int(input("Enter the first number "))
NUM2 = int(input("Enter the second number "))
sum=NUM1+NUM2
print("The sum of ",NUM1," + ",NUM2," is", sum)

#QUESTION NO 2: Create a variable, message, and assign it a string value. Append another string, " World!", to it and print the result.

message = "Hello"
print(message)
message += " World!"
print(message)

#QUESTION NO 3: Define a variable, is_python_fun, and assign it a boolean value. Print a statement based on whether Python is considered fun.
is_python_fun = True
if is_python_fun:
    print("Python is fun!")
else:
    print("Python is not fun.")

#QUESTION NO 4: Create a list, fruits, with three different fruit names. Print the list and then add a new fruit to it. Print the updated list.
# Creating a list named 'fruits' with 3 different names of fruit
fruits = ["Apple", "Banana", "Orange"]

# List of fruits before append function
print("Original list of fruits:", fruits)

# New fruit added using append function
fruits.append("Grapes")

# Printing list after append function
print("Updated list of fruits:", fruits)

#QUESTION NO 5: Declare a variable, price, with a floating-point value. Convert it to an integer and print both the original and converted values.
# Variable declared with floating-point value named 'price'
price = 19.99

# Converting value to an integer
converted_price = int(price)

# Printing both the original and converted values
print("Original price:", price)
print("Converted price:", converted_price)

#QUESTION NO 6: Create a dictionary, student_info, with keys for 'name', 'age', and 'grade'. Assign corresponding values and print the dictionary

# Creating a dictionary named 'student_info' with keys for 'name', 'age', and 'grade'
student_info = {'name': 'John Doe','age': 20,'grade': 'A'}

# Printing the dictionary
print("Student Information:")
print(student_info)

#QUESTION NO 7: Write a program that takes user input for their age and prints a message addressing their age group (e.g., "Teenager," "Adult").
# Inputting age
user_age = int(input("Enter your age: "))

# Checking the age group
if 0 <= user_age <= 12:
    print("You are a Child.")
elif 13 <= user_age <= 19:
    print("You are a Teenager.")
elif 20 <= user_age <= 64:
    print("You are an Adult.")
else:
    print("You are a Senior Citizen.")

#QUESTION NO 8: Define a complex number variable, comp_num, with a real and imaginary part. Print both parts separately.

# Defining a complex number variable named 'comp_num' with a real and imaginary part
comp_num = 6 + 7j  # The real part is 6, and the imaginary part is 7

# Printing both parts separately
print("Real part:", comp_num.real)
print("Imaginary part:", comp_num.imag)

#QUESTION NO 9: Combine two strings using string concatenation, and then use string interpolation to include the length of the resulting string in a print statement.

# Two strings
string1 = "Your"
string2 = " Student!"

# Combining two strings using string concatenation
combined_string = string1 + string2

# Using string interpolation to include the length of the resulting string in a print statement
print(f"The combined string is: {combined_string}. Its length is {len(combined_string)} characters.")

#QUESTION NO 10: Create a tuple, days_of_week, with the names of the days. Access and print the third day of the week.

# Creating a tuple named 'days_of_week' with the names of the days
days_of_week = ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')

# Accessing and printing the third day of the week (index 2 since indexing starts from 0)
third_day = days_of_week[2]
print("The third day of the week is:", third_day)

